[package]
name = "basic-init"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "basic-init"
path = "src/main.rs"

[dependencies]
dpdk = { path = "../../dpdk" }
