[workspace]
members = [
    "dpdk-sys",
    "dpdk",
    "examples/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sqfzy/dpdk-sq"
authors = ["sqfzy"]

[workspace.dependencies]
libc = "0.2"
thiserror = "1.0"
